insert into
  metode_pembayaran(jenis_pembayaran)
values
  ('Transfer Bank'),
  ('Kartu Kredit'),
  ('OVO'),
  ('GoPay'),
  ('Dana'),
  ('LinkAja'),
  ('QRIS'),
  ('Alfamart'),
  ('Indomaret'),
  ('Klik BCA'),
  ('BCA Virtual Account'),
  ('BNI Virtual Account'),
  ('Mandiri Virtual Account'),
  ('CIMB Niaga Virtual Account'),
  ('BCA KlikPay'),
  ('BRI e-Pay'),
  ('Permata Bank'),
  ('Maybank'),
  ('Panin Bank'),
  ('Danamon'),
  ('HSBC'),
  ('Standard Chartered'),
  ('Bank Mega'),
  ('Bank Central Asia'),
  ('Bank Rakyat Indonesia'),
  ('Bank Negara Indonesia'),
  ('Bank Mandiri'),
  ('Bank Tabungan Negara'),
  ('Bank CIMB Niaga'),
  ('Bank OCBC NISP'),
  ('Bank Jago'),
  ('Paypal'),
  ('Visa'),
  ('Mastercard'),
  ('American Express'),
  ('JCB'),
  ('Discover'),
  ('Diners Club'),
  ('UnionPay'),
  ('Bitcoin'),
  ('Ethereum'),
  ('Binance Coin'),
  ('Dogecoin'),
  ('Tether'),
  ('Cardano'),
  ('XRP'),
  ('Polkadot'),
  ('Solana'),
  ('Shiba Inu'),
  ('Cash on Delivery (COD)');