insert into
  kategori(jenis_kategori)
values
  ('Teknologi'),
  ('Pakaian'),
  ('Perawatan Kecantikan'),
  ('Perlengkapan Rumah Tangga'),
  ('Pakaian dan Aksesoris Muslim'),
  ('Pakaian & Aksesoris Wanita'),
  ('Handphone & Aksesoris'),
  ('Perlengkapan Pesta & Souvenir'),
  ('Pakaian & Aksesoris Anak'),
  ('Perlengkapan Otomotif'),
  ('Pakaian & Aksesoris Pria'),
  ('Peralatan Rumah Tangga'),
  ('Makanan & Makanan'),
  ('Perlengkapan Bayi'),
  ('Alat Elektronik'),
  ('Mainan & Hobi'),
  ('Tas Wanita'),
  ('Jam Tangan'),
  ('Alat Tulis Kantor'),
  ('Sepatu Wanita'),
  ('Perlengkapan Olahraga Outdoor'),
  ('Serba-serbi'),
  ('Komputer & Aksesoris'),
  ('Tas Pria'),
  ('Sepatu Pria'),
  ('Kamera & Aksesoris'),
  ('Motor & Aksesoris Motor'),
  ('Peralatan Dapur'),
  ('Perawatan Hewan'),
  ('Perawatan Tubuh'),
  ('Peralatan Pertukangan'),
  ('Peralatan Industri'),
  ('Mobil & Aksesoris Mobil'),
  ('Sepeda & Aksesoris'),
  ('Peralatan Olahraga'),
  ('Buku'),
  ('Pelengkapan Kantor'),
  ('Film & Musik'),
  ('Aksesoris Gaming'),
  ('Pakaian Wanita'),
  ('Pakaian Pria'),
  ('Pakaian Anak-Anak'),
  ('Sepatu Wanita'),
  ('Sepatu Pria'),
  ('Sepatu Anak-Anak'),
  ('Aksesoris Wanita'),
  ('Aksesoris Pria'),
  ('Aksesoris Elektronik'),
  ('Peralatan Olahraga'),
  ('Alat Musik'),
  ('Mainan dan Hobi'),
  ('Perabot Rumah Tangga'),
  ('Produk Kecantikan dan Perawatan Kulit'),
  ('Perlengkapan Bayi dan Ibu Hamil'),
  ('Makanan dan Minuman'),
  ('Buku dan Majalah'),
  ('Elektronik Konsumen'),
  ('Perlengkapan Kantor dan Sekolah'),
  ('Barang Antik dan Koleksi'),
  ('Produk Kesehatan dan Kesejahteraan'),
  ('Perhiasan dan Jam Tangan'),
  ('Tas dan Dompet'),
  ('Alat Tulis dan Kerajinan Tangan'),
  ('Peralatan Kesehatan dan Kedokteran'),
  ('Peralatan Elektronik'),
  ('Produk Keamanan dan Keamanan Rumah'),
  ('Alat dan Perlengkapan Otomotif'),
  ('Peralatan Taman dan Outdoor'),
  ('Bunga dan Tanaman Hias'),
  ('Kamera dan Fotografi'),
  ('Peralatan Studio dan Rekaman'),
  ('Perlengkapan Pesta dan Acara'),
  ('Peralatan Perjalanan dan Liburan'),
  ('Peralatan Bangunan dan Perbaikan Rumah'),
  ('Produk Digital dan Kursus Online'),
  ('Produk Peternakan dan Pet Supplies'),
  ('Peralatan Petualangan dan Survival'),
  ('Peralatan Pemancingan dan Aksesoris'),
  ('Produk Kerajinan Tangan dan Karya Seni'),
  ('Produk Kebun dan Perkebunan'),
  ('Peralatan Listrik dan Mesin'),
  ('Perlengkapan Bar dan Anggur'),
  ('Produk Pembersih dan Kimia Rumah'),
  ('Produk Peralatan Dapur'),
  ('Peralatan Perawatan Hewan Peliharaan'),
  ('Perlengkapan Perawatan Mobil'),
  ('Perlengkapan Pencahayaan'),
  ('Produk Keselamatan Industri'),
  ('Peralatan Komunikasi dan Jaringan');