INSERT INTO
  user (nama, role, gender)
VALUES
  ('Dasa Hidayanto', 'admin', 'wanita'),
  ('Adiarja Abimanyu', 'admin', 'wanita'),
  ('Maya Purnawati', 'admin', 'wanita'),
  ('Silvia Oktaviani', 'admin', 'pria'),
  ('Febrina Uyainah', 'admin', 'wanita'),
  ('Halima Azizah', 'customer', 'pria'),
  ('Virman Ardana', 'customer', 'wanita'),
  ('Lintang Andriani', 'customer', 'pria'),
  ('Kayun Sihombing', 'customer', 'pria'),
  ('Calista Azizah', 'customer', 'wanita'),
  ('Rosa Azzahra', 'customer', 'pria'),
  ('Ade Nathania', 'customer', 'pria'),
  ('Ellis Utami', 'customer', 'wanita'),
  ('Abyasa Narpati', 'customer', 'pria'),
  ('Humaira Elvina', 'customer', 'pria'),
  ('Danu Sihotang', 'customer', 'pria'),
  ('Fitriani Aurelia', 'customer', 'wanita'),
  ('Lintang Nasyidah', 'customer', 'pria'),
  ('Devi Pratiwi', 'customer', 'pria'),
  ('Rizki Nugraha', 'customer', 'pria'),
  ('Budi Yanuar', 'customer', 'wanita'),
  ('Garang Santoso', 'customer', 'pria'),
  ('Malika Elvina S.H.', 'customer', 'pria'),
  ('Kania Rachmawati', 'customer', 'wanita'),
  ('Kania Ramadhani', 'customer', 'wanita'),
  ('Maryanto Setiawan', 'customer', 'pria'),
  ('Gawati Safitri', 'customer', 'wanita'),
  ('Reza Wicaksono', 'customer', 'pria'),
  ('Purwa Situmorang', 'customer', 'wanita'),
  ('Amalia Melinda', 'customer', 'pria'),
  ('Ratih Farida', 'customer', 'pria'),
  ('Hani Suryatmi', 'customer', 'wanita'),
  ('Yance Wijayanti', 'customer', 'wanita'),
  ('Okta Abimanyu S.Ked', 'customer', 'wanita'),
  (
    'Anggun Puspasari S.IP',
    'customer',
    'wanita'
  ),
  ('Vicky Melani', 'customer', 'pria'),
  ('Jaka Agustian', 'customer', 'wanita'),
  ('Luis Airlangga', 'customer', 'pria'),
  ('Tina Hariyah S.I.Kom', 'customer', 'wanita'),
  ('Hendri Hermawan', 'customer', 'pria'),
  ('Caraka Hidayanto', 'customer', 'pria'),
  ('Puspita Permata', 'customer', 'wanita'),
  ('Bella Utami M.Pd', 'customer', 'pria'),
  ('Cengkir Megantara', 'customer', 'wanita'),
  ('Laksana Ardianto', 'customer', 'pria'),
  ('Arta Adriansyah S.IP', 'customer', 'pria'),
  ('Dimas Habibi', 'customer', 'pria'),
  ('Gina Hassanah', 'customer', 'pria'),
  ('Kamal Mustofa', 'customer', 'wanita'),
  ('Nova Riyanti', 'customer', 'wanita'),
  ('Niyaga Setiawan', 'customer', 'wanita'),
  ('Gamblang Hakim', 'customer', 'wanita'),
  ('Ismail Rayhan', 'customer', 'pria'),
  ('Kamila Riyanti', 'customer', 'wanita'),
  ('Yono Prasetyo', 'customer', 'pria'),
  (
    'Irnanto Prasasta M.Kom.',
    'customer',
    'wanita'
  ),
  ('Abyasa Ramadan', 'customer', 'wanita'),
  ('Maria Haryanti', 'customer', 'wanita'),
  ('Vanya Febrianti', 'customer', 'pria'),
  ('Puspita Kusmawati', 'customer', 'wanita'),
  ('Luwes Mangunsong', 'customer', 'pria'),
  ('Genta Mandasari', 'customer', 'pria'),
  ('Azalea Saraswati', 'customer', 'pria'),
  ('Gara Antoni', 'customer', 'wanita'),
  ('Ditya Mustika', 'customer', 'pria');